project:
  type: website
  output-dir: "../docs/fr"

website:
  back-to-top-navigation: true
  navbar:
    pinned: false
    logo: /images/logo.png
    left:
      - text: Substituts du tabac
        href: smoking.qmd
      - text: Recrutement
        href: Recruitment.qmd
      - text: Documents
        menu: 
          - text: Formulaires de consentement
            href: Materials.qmd
          - text: Protocole
            href: Protocol.qmd
          - text: Brochure produit
            href: Brochure.qmd
      - text: Partenaires
        href: Funding.qmd
      - text: Actualités
        href: news.qmd
      - text: "Équipe"
        href: Principal.qmd 
    right: 
      - text: "🌍 Langue"
        menu:
          - text: "English"
            href: ../en/index.html
          - text: "Deutsch"
            href: ../de/index.html
      - icon: envelope
        text: Email
        href: mailto:christof.schoenenberger@usb.ch
      - icon: folder
        text: Registry
        href: https://clinicaltrials.gov/study/NCT06789692?cond=NCT06789692&rank=1
      - icon: github
        href: https://github.com/christofmanuel/RETUNE_website
  page-footer: © 2025  &middot; Made with [![](https://www.r-project.org/logo/Rlogo.png){fig-alt="R" width=25px}](https://www.r-project.org) and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
  search:
    location: navbar
    type: textbox
    
html:
  theme: quartz
  backgroundcolor: "#E6F0FA"  # Fresh, soft blue with a hint of vibrancy for a lively background
  mainfont: "Arial, sans-serif"
  fontsize: 1.6rem
  fontcolor: "#123456"  # Deep indigo for a richer text color that stands out
  footer: "#102A43"   # Dark navy with a hint of warmth for an inviting footer
  icon:
    color: "#3A7BD5"   # Bright, electric blue for dynamic icons
  header:
    background-color: "#0F4471"  # Bold, vibrant navy for a strong and modern header
    text-color: "#FFFFFF"  # Crisp white text for sharp contrast
  link:
    color: "#2684FF"  # Vivid blue for eye-catching links
    hover-color: "#1A5DAB"  # Deep royal blue for hover effects, adding depth
  button:
    background-color: "#2684FF"  # Bright blue buttons to draw attention
    text-color: "#FFFFFF"  # White text for clarity
    border-radius: 12px  # Extra-rounded corners for a bold, modern look
    border-color: "#123456"  # Subtle indigo border to add sophistication
  border:
    color: "#D1D9E6"  # Soft blue-gray for gentle but noticeable separation
    radius: 12px  # Rounded corners to maintain the modern, vibrant feel
  alert:
    background-color: "#CCE7FF"  # Light, vibrant blue for noticeable yet pleasant alerts
    text-color: "#0F4471"  # Strong navy text for alerts to ensure readability
  section:
    background-color: "#F0F4FF"  # Very light blue to keep sections airy and open
    padding: 30px  # Generous padding for a more spacious and comfortable layout
    margin-bottom: 30px  # Increased spacing for a clearer visual separation
style: css
    
editor: visual

