---
title: "Recrutement"
---


```{r setup, include=FALSE}
library(plotly)
library(tidyverse)
library(lubridate)
library(readxl)
```

```{r fig1, echo=FALSE}
#load data set
df <- read_excel("../RETUNE_recruitment.xlsx")

#Make sure that Date is in date format 
df <- df %>% 
 mutate(Date = as.Date(Date))

#Sort from oldest to newest 
df <- df %>% 
   arrange(Date)

#Create variable with total number of randomized participants 
df <- df %>%
  mutate(Total = row_number())

#Create a plot 
plot_total <- plot_ly() %>%
  # First trace: TotalIntervention
  add_trace(
    data = df,
    x = ~Date,
    y = ~Total,
    type = "scatter",
    mode = "lines+markers",
    fill = "tozeroy",         # fill area down to y=0
    name = "Total Intervention"
  ) %>%
  layout(
    title = "Recrutement au fil du temps",
    xaxis = list(title = "Date", type = "date"),
    yaxis = list(title = "Nombre de participants")
  )

plot_total
```


<!-- Add some space with a div or br tags --> <div style="margin-top: 150px;"></div>

```{r fig2, echo=FALSE}
#Create a data set with people randomized to intervention group
df_intervention <- df %>%
  filter(Intervention == 1) %>%
  mutate(TotalIntervention = row_number())

#Create a varible for total uptake over time 
df_intervention <- df_intervention %>%   
  arrange(Date) %>%   # Ensure rows are in chronological order
  mutate(Uptake = as.numeric(Uptake)) %>% # Convert Uptake to numeric just in case it's not (e.g. factor)
  mutate(Totaluptake = cumsum(Uptake))   # Create a running sum of Uptake

#Create a plot 
p_intervention <- plot_ly() %>%
  # First trace: TotalIntervention
  add_trace(
    data = df_intervention,
    x = ~Date,
    y = ~TotalIntervention,
    type = "scatter",
    mode = "lines+markers",
    fill = "tozeroy",         # fill area down to y=0
    name = "Total groupe d'intervention"
  ) %>%
  # Second trace: Totaluptake
  add_trace(
    data = df_intervention,
    x = ~Date,
    y = ~Totaluptake,
    type = "scatter",
    mode = "lines+markers",
    fill = "tozeroy",
    name = "Total Uptake groupe d'intervention"
  ) %>%
  layout(
      title = "Groupe d'intervention au fil du temps",
      xaxis = list(title = "Date", type = "date"),
      yaxis = list(title = "Nombre de participants")
  )

#This is the code to add a dashed horizontal line for the target uptake 
#p_intervention <- p_intervention %>%
#  layout(
#   shapes = list(
#    list(
#       type = "line",
#       xref = "paper", x0 = 0, x1 = 1,
#       yref = "y", y0 = 256, y1 = 256,
#      line = list(color = "black", dash = "dash")
#     )
#   ),
#   annotations = list(
#     list(
#       xref = "paper", x = 0.98,  # near right edge
#       yref = "y",     y = 256,
#       xanchor = "left",
#       text = "Target = 256",
#       showarrow = FALSE
#     )
#   )
# )

p_intervention
```